relaychain:
  endpoint: wss://paseo-rpc.dwellir.com
  port: 8000
  db: ./test-db-relay.sqlite

parachains:
  - endpoint: wss://paseo-asset-hub-rpc.dwellir.com
    paraId: 1000
    port: 8001
    db: ./test-db-parachain.sqlite
