url: https://polkadot-developers.github.io
baseurl: /polkadot-cookbook

plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

titles_from_headings:
  enabled: true
  strip_title: true

defaults:
  - scope:
      path: ""
    values:
      layout: doc

exclude:
  - README.md
